// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt6CmvyB6bIR48AnjNky2l0U8o36ex-bE',
    appId: '1:925578891959:web:71b55eaf40acdac6bdb332',
    messagingSenderId: '925578891959',
    projectId: 'dowajo2-743ab',
    authDomain: 'dowajo2-743ab.firebaseapp.com',
    storageBucket: 'dowajo2-743ab.appspot.com',
    measurementId: 'G-B1XJR7KBVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1vz1SOkyuXVGkd9r1cRVSz9ejvt2iIBY',
    appId: '1:925578891959:android:3eb5e14997df47d6bdb332',
    messagingSenderId: '925578891959',
    projectId: 'dowajo2-743ab',
    storageBucket: 'dowajo2-743ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk7sjwcrDgO6nJE2r8mx7Gm1HmLb2v-dM',
    appId: '1:925578891959:ios:a6fa9ba95de59674bdb332',
    messagingSenderId: '925578891959',
    projectId: 'dowajo2-743ab',
    storageBucket: 'dowajo2-743ab.appspot.com',
    iosBundleId: 'com.dowajo.myapp.dowajo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk7sjwcrDgO6nJE2r8mx7Gm1HmLb2v-dM',
    appId: '1:925578891959:ios:a6fa9ba95de59674bdb332',
    messagingSenderId: '925578891959',
    projectId: 'dowajo2-743ab',
    storageBucket: 'dowajo2-743ab.appspot.com',
    iosBundleId: 'com.dowajo.myapp.dowajo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt6CmvyB6bIR48AnjNky2l0U8o36ex-bE',
    appId: '1:925578891959:web:1088c5ea4833ddcfbdb332',
    messagingSenderId: '925578891959',
    projectId: 'dowajo2-743ab',
    authDomain: 'dowajo2-743ab.firebaseapp.com',
    storageBucket: 'dowajo2-743ab.appspot.com',
    measurementId: 'G-N78P4JT7WW',
  );
}
